name: Docker CI/CD Pipeline with Semantic Versioning

on:
  pull_request:
    branches:
      - main
      - homolog

  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/conversao-distancia

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Run Application Tests
        run: |
          docker run --rm -d -p 8282:5000 --name test-container $IMAGE_NAME:latest
          sleep 5  # Espera o contêiner iniciar
          curl -f http://localhost:8282/convert?from=meters&to=kilometers&value=1000
          docker stop test-container

  version-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Increment Semantic Version for Staging
        id: tag
        uses: anothrNick/github-tag-action@v1.37.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          semver: preminor  # Incremento menor de pré-lançamento para staging

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Staging Image
        run: |
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.tag.outputs.new_tag }}-staging
          docker push $IMAGE_NAME:${{ steps.tag.outputs.new_tag }}-staging

  version-homolog:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged
    steps:
      - name: Increment Semantic Version for Homolog
        id: tag
        uses: anothrNick/github-tag-action@v1.37.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          semver: minor  # Incremento menor para homolog

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Homolog Image
        run: |
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.tag.outputs.new_tag }}-homolog
          docker push $IMAGE_NAME:${{ steps.tag.outputs.new_tag }}-homolog

  version-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Increment Semantic Version for Production
        id: tag
        uses: anothrNick/github-tag-action@v1.37.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          semver: patch  # Incremento de patch para produção

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Production Image
        run: |
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.tag.outputs.new_tag }}
          docker push $IMAGE_NAME:${{ steps.tag.outputs.new_tag }}
