name: CI/CD for Production

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/conversao-distancia

jobs:
  build-and-deploy-production:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Production
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Run Application Tests
        run: |
          # Inicia o contêiner
          docker run --rm -d -p 5000:5000 --name test-container $IMAGE_NAME:latest

          # Aguardar o contêiner iniciar completamente
          echo "Aguardando a inicialização do contêiner..."
          sleep 10

          # Testa a aplicação
          if curl -f http://localhost:5000/convert?from=meters&to=kilometers&value=1000; then
            echo "Teste de API bem-sucedido!"
          else
            echo "Erro na API. Logs do contêiner:"
            docker logs test-container
            exit 1
          fi

          # Para o contêiner após os testes
          docker stop test-container
